/** Bootstrap data only. Deployed matching reads the database catalog. */
export const EDUCATION_CATALOG_SEED = [
  {
    key: "computer_science",
    kind: "field",
    labelEn: "Computer Science",
    labelHe: "מדעי המחשב",
    aliases: ["Computer Sciences", "CS", "מדמח", "מדמ״ח"],
  },
  {
    key: "software_engineering",
    kind: "field",
    labelEn: "Software Engineering",
    labelHe: "הנדסת תוכנה",
    aliases: [],
  },
  {
    key: "electrical_engineering",
    kind: "field",
    labelEn: "Electrical Engineering",
    labelHe: "הנדסת חשמל",
    aliases: [],
  },
  {
    key: "mechanical_engineering",
    kind: "field",
    labelEn: "Mechanical Engineering",
    labelHe: "הנדסת מכונות",
    aliases: [],
  },
  {
    key: "accounting",
    kind: "field",
    labelEn: "Accounting",
    labelHe: "חשבונאות",
    aliases: ["Accountancy"],
  },
  {
    key: "business",
    kind: "field",
    labelEn: "Business Administration",
    labelHe: "מנהל עסקים",
    aliases: ["MBA"],
  },
  {
    key: "information_systems",
    kind: "field",
    labelEn: "Information Systems",
    labelHe: "מערכות מידע",
    aliases: [],
  },
  {
    key: "mathematics",
    kind: "field",
    labelEn: "Mathematics",
    labelHe: "מתמטיקה",
    aliases: ["Math", "Maths"],
  },
  {
    key: "physics",
    kind: "field",
    labelEn: "Physics",
    labelHe: "פיזיקה",
    aliases: [],
  },
  { key: "law", kind: "field", labelEn: "Law", labelHe: "משפטים", aliases: [] },
  {
    key: "psychology",
    kind: "field",
    labelEn: "Psychology",
    labelHe: "פסיכולוגיה",
    aliases: [],
  },
  {
    key: "biology",
    kind: "field",
    labelEn: "Biology",
    labelHe: "ביולוגיה",
    aliases: [],
  },
  {
    key: "drivers_license",
    kind: "qualification",
    labelEn: "Driver's license",
    labelHe: "רישיון נהיגה",
    aliases: ["Driving license"],
  },
  {
    key: "cpa",
    kind: "qualification",
    labelEn: "CPA",
    labelHe: "רואה חשבון מוסמך",
    aliases: ["Certified Public Accountant"],
  },
  {
    key: "pmp",
    kind: "qualification",
    labelEn: "PMP",
    labelHe: "הסמכת PMP",
    aliases: ["Project Management Professional"],
  },
  {
    key: "cissp",
    kind: "qualification",
    labelEn: "CISSP",
    labelHe: "הסמכת CISSP",
    aliases: [],
  },
  {
    key: "ccna",
    kind: "qualification",
    labelEn: "CCNA",
    labelHe: "הסמכת CCNA",
    aliases: [],
  },
  {
    key: "ccnp",
    kind: "qualification",
    labelEn: "CCNP",
    labelHe: "הסמכת CCNP",
    aliases: [],
  },
  {
    key: "registered_nurse",
    kind: "qualification",
    labelEn: "Registered Nurse",
    labelHe: "אחות מוסמכת",
    aliases: ["Nursing license", "אח מוסמך"],
  },
] as const;
