/** Bootstrap data only. Deployed matching reads the database catalog. */
export const EDUCATION_CATALOG_SEED = [
  {
    key: "computer_science",
    kind: "field",
    labelEn: "Computer Science",
    labelHe: "מדעי המחשב",
    aliases: ["Computer Sciences", "CS", "מדמח", "מדמ״ח"],
  },
  {
    key: "software_engineering",
    kind: "field",
    labelEn: "Software Engineering",
    labelHe: "הנדסת תוכנה",
    aliases: [],
  },
  {
    key: "electrical_engineering",
    kind: "field",
    labelEn: "Electrical Engineering",
    labelHe: "הנדסת חשמל",
    aliases: [],
  },
  {
    key: "mechanical_engineering",
    kind: "field",
    labelEn: "Mechanical Engineering",
    labelHe: "הנדסת מכונות",
    aliases: [],
  },
  {
    key: "accounting",
    kind: "field",
    labelEn: "Accounting",
    labelHe: "חשבונאות",
    aliases: ["Accountancy"],
  },
  {
    key: "business",
    kind: "field",
    labelEn: "Business Administration",
    labelHe: "מנהל עסקים",
    aliases: ["MBA"],
  },
  {
    key: "information_systems",
    kind: "field",
    labelEn: "Information Systems",
    labelHe: "מערכות מידע",
    aliases: [],
  },
  {
    key: "mathematics",
    kind: "field",
    labelEn: "Mathematics",
    labelHe: "מתמטיקה",
    aliases: ["Math", "Maths"],
  },
  {
    key: "physics",
    kind: "field",
    labelEn: "Physics",
    labelHe: "פיזיקה",
    aliases: [],
  },
  { key: "law", kind: "field", labelEn: "Law", labelHe: "משפטים", aliases: [] },
  {
    key: "psychology",
    kind: "field",
    labelEn: "Psychology",
    labelHe: "פסיכולוגיה",
    aliases: [],
  },
  {
    key: "biology",
    kind: "field",
    labelEn: "Biology",
    labelHe: "ביולוגיה",
    aliases: [],
  },
  {
    key: "drivers_license",
    kind: "qualification",
    labelEn: "Driver's license",
    labelHe: "רישיון נהיגה",
    aliases: ["Driving license"],
  },
  {
    key: "cpa",
    kind: "qualification",
    labelEn: "CPA",
    labelHe: "רואה חשבון מוסמך",
    aliases: ["Certified Public Accountant"],
  },
  {
    key: "pmp",
    kind: "qualification",
    labelEn: "PMP",
    labelHe: "הסמכת PMP",
    aliases: ["Project Management Professional"],
  },
  {
    key: "cissp",
    kind: "qualification",
    labelEn: "CISSP",
    labelHe: "הסמכת CISSP",
    aliases: [],
  },
  {
    key: "ccna",
    kind: "qualification",
    labelEn: "CCNA",
    labelHe: "הסמכת CCNA",
    aliases: [],
  },
  {
    key: "ccnp",
    kind: "qualification",
    labelEn: "CCNP",
    labelHe: "הסמכת CCNP",
    aliases: [],
  },
  {
    key: "registered_nurse",
    kind: "qualification",
    labelEn: "Registered Nurse",
    labelHe: "אחות מוסמכת",
    aliases: ["Nursing license", "אח מוסמך"],
  },
  ...[
    ["industrial_engineering", "Industrial Engineering", "הנדסת תעשייה וניהול"],
    ["civil_engineering", "Civil Engineering", "הנדסה אזרחית"],
    ["chemical_engineering", "Chemical Engineering", "הנדסה כימית"],
    ["biomedical_engineering", "Biomedical Engineering", "הנדסה ביו-רפואית"],
    ["economics", "Economics", "כלכלה"],
    ["communications", "Communications", "תקשורת"],
    ["education", "Education", "חינוך"],
    ["social_work", "Social Work", "עבודה סוציאלית"],
    ["nursing", "Nursing", "סיעוד"],
    ["medicine", "Medicine", "רפואה"],
    ["pharmacy", "Pharmacy", "רוקחות"],
    ["physiotherapy", "Physiotherapy", "פיזיותרפיה"],
    ["chemistry", "Chemistry", "כימיה"],
    ["biotechnology", "Biotechnology", "ביוטכנולוגיה"],
    ["statistics", "Statistics", "סטטיסטיקה"],
    ["data_science", "Data Science", "מדעי הנתונים"],
    ["architecture", "Architecture", "אדריכלות"],
    ["graphic_design", "Graphic Design", "עיצוב גרפי"],
    ["interior_design", "Interior Design", "עיצוב פנים"],
    ["political_science", "Political Science", "מדעי המדינה"],
    ["sociology", "Sociology", "סוציולוגיה"],
    ["english", "English Studies", "לימודי אנגלית"],
    ["history", "History", "היסטוריה"],
    ["logistics", "Logistics", "לוגיסטיקה"],
  ].map(([key, labelEn, labelHe]) => ({
    key,
    kind: "field" as const,
    labelEn,
    labelHe,
    aliases: [] as string[],
  })),
  ...[
    [
      "aws_cloud_practitioner",
      "AWS Certified Cloud Practitioner",
      "הסמכת AWS Cloud Practitioner",
    ],
    [
      "aws_solutions_architect",
      "AWS Certified Solutions Architect",
      "הסמכת AWS Solutions Architect",
    ],
    [
      "azure_fundamentals",
      "Microsoft Azure Fundamentals",
      "הסמכת Azure Fundamentals",
    ],
    [
      "google_cloud_architect",
      "Google Professional Cloud Architect",
      "הסמכת Google Cloud Architect",
    ],
    ["cka", "Certified Kubernetes Administrator", "הסמכת CKA"],
    ["comptia_a_plus", "CompTIA A+", "הסמכת CompTIA A+"],
    ["comptia_security_plus", "CompTIA Security+", "הסמכת CompTIA Security+"],
    ["scrum_master", "Certified ScrumMaster", "הסמכת Scrum Master"],
    ["istqb", "ISTQB", "הסמכת ISTQB"],
    ["payroll", "Payroll Certification", "הסמכת חשב שכר"],
    ["bookkeeping", "Bookkeeping Certification", "הסמכת הנהלת חשבונות"],
    ["teaching", "Teaching Certificate", "תעודת הוראה"],
    ["electrician", "Electrician License", "רישיון חשמלאי"],
    ["forklift", "Forklift License", "רישיון מלגזה"],
  ].map(([key, labelEn, labelHe]) => ({
    key,
    kind: "qualification" as const,
    labelEn,
    labelHe,
    aliases: [] as string[],
  })),
] as const;
