export type CatalogSeedItem = {
  kind: "jobTitle" | "skill";
  slug: string;
  labelEn: string;
  labelHe: string;
  aliases?: string[];
  priority: number;
};

const jobTitles: Omit<CatalogSeedItem, "kind">[] = [
  {
    slug: "software-engineer",
    labelEn: "Software Engineer",
    labelHe: "מהנדס תוכנה",
    aliases: ["Software Developer", "מפתח תוכנה", "Programmer", "מתכנת"],
    priority: 100,
  },
  {
    slug: "frontend-engineer",
    labelEn: "Frontend Engineer",
    labelHe: "מפתח Frontend",
    aliases: ["Front-end Developer", "מפתח פרונטאנד"],
    priority: 99,
  },
  {
    slug: "backend-engineer",
    labelEn: "Backend Engineer",
    labelHe: "מפתח Backend",
    aliases: ["Back-end Developer", "מפתח בקאנד"],
    priority: 98,
  },
  {
    slug: "fullstack-engineer",
    labelEn: "Full-stack Engineer",
    labelHe: "מפתח Full-stack",
    aliases: ["Full Stack Developer", "מפתח פול סטאק"],
    priority: 97,
  },
  {
    slug: "mobile-developer",
    labelEn: "Mobile Developer",
    labelHe: "מפתח מובייל",
    aliases: ["iOS Developer", "Android Developer"],
    priority: 96,
  },
  {
    slug: "devops-engineer",
    labelEn: "DevOps Engineer",
    labelHe: "מהנדס DevOps",
    priority: 95,
  },
  {
    slug: "data-engineer",
    labelEn: "Data Engineer",
    labelHe: "מהנדס נתונים",
    priority: 94,
  },
  {
    slug: "data-scientist",
    labelEn: "Data Scientist",
    labelHe: "מדען נתונים",
    priority: 93,
  },
  {
    slug: "machine-learning-engineer",
    labelEn: "Machine Learning Engineer",
    labelHe: "מהנדס למידת מכונה",
    aliases: ["ML Engineer", "AI Engineer"],
    priority: 92,
  },
  {
    slug: "qa-engineer",
    labelEn: "QA Engineer",
    labelHe: "מהנדס בדיקות",
    aliases: ["Software Tester", "בודק תוכנה"],
    priority: 91,
  },
  {
    slug: "automation-engineer",
    labelEn: "Automation Engineer",
    labelHe: "מהנדס אוטומציה",
    aliases: ["QA Automation Engineer"],
    priority: 90,
  },
  {
    slug: "security-engineer",
    labelEn: "Security Engineer",
    labelHe: "מהנדס אבטחת מידע",
    aliases: ["Cybersecurity Engineer"],
    priority: 89,
  },
  {
    slug: "cloud-engineer",
    labelEn: "Cloud Engineer",
    labelHe: "מהנדס ענן",
    priority: 88,
  },
  {
    slug: "solutions-architect",
    labelEn: "Solutions Architect",
    labelHe: "ארכיטקט פתרונות",
    priority: 87,
  },
  {
    slug: "engineering-manager",
    labelEn: "Engineering Manager",
    labelHe: "מנהל פיתוח",
    aliases: ["R&D Manager", "מנהל הנדסה"],
    priority: 86,
  },
  {
    slug: "product-manager",
    labelEn: "Product Manager",
    labelHe: "מנהל מוצר",
    priority: 85,
  },
  {
    slug: "project-manager",
    labelEn: "Project Manager",
    labelHe: "מנהל פרויקטים",
    priority: 84,
  },
  {
    slug: "program-manager",
    labelEn: "Program Manager",
    labelHe: "מנהל תוכניות",
    priority: 83,
  },
  {
    slug: "product-designer",
    labelEn: "Product Designer",
    labelHe: "מעצב מוצר",
    priority: 82,
  },
  {
    slug: "ux-ui-designer",
    labelEn: "UX/UI Designer",
    labelHe: "מעצב UX/UI",
    priority: 81,
  },
  {
    slug: "graphic-designer",
    labelEn: "Graphic Designer",
    labelHe: "מעצב גרפי",
    priority: 80,
  },
  {
    slug: "business-analyst",
    labelEn: "Business Analyst",
    labelHe: "אנליסט עסקי",
    priority: 79,
  },
  {
    slug: "data-analyst",
    labelEn: "Data Analyst",
    labelHe: "אנליסט נתונים",
    priority: 78,
  },
  {
    slug: "financial-analyst",
    labelEn: "Financial Analyst",
    labelHe: "אנליסט פיננסי",
    priority: 77,
  },
  {
    slug: "marketing-manager",
    labelEn: "Marketing Manager",
    labelHe: "מנהל שיווק",
    priority: 76,
  },
  {
    slug: "ecommerce-manager",
    labelEn: "E-commerce Manager",
    labelHe: "מנהל E-commerce",
    aliases: [
      "Ecommerce Manager",
      "E-Commerce Manager",
      "מנהל איקומרס",
      "מנהל מסחר אלקטרוני",
    ],
    priority: 76,
  },
  {
    slug: "website-manager",
    labelEn: "Website Manager",
    labelHe: "מנהל אתר",
    aliases: ["Web Manager", "E-commerce Website Manager", "מנהל אתר איקומרס"],
    priority: 76,
  },
  {
    slug: "ecommerce-operations-manager",
    labelEn: "E-commerce Operations Manager",
    labelHe: "מנהל תפעול E-commerce",
    aliases: [
      "Ecommerce Operations Manager",
      "Digital Commerce Operations Manager",
      "מנהל תפעול איקומרס",
    ],
    priority: 76,
  },
  {
    slug: "digital-marketing-specialist",
    labelEn: "Digital Marketing Specialist",
    labelHe: "מומחה שיווק דיגיטלי",
    priority: 75,
  },
  {
    slug: "content-writer",
    labelEn: "Content Writer",
    labelHe: "כותב תוכן",
    priority: 74,
  },
  {
    slug: "sales-manager",
    labelEn: "Sales Manager",
    labelHe: "מנהל מכירות",
    priority: 73,
  },
  {
    slug: "account-manager",
    labelEn: "Account Manager",
    labelHe: "מנהל לקוחות",
    priority: 72,
  },
  {
    slug: "customer-success-manager",
    labelEn: "Customer Success Manager",
    labelHe: "מנהל הצלחת לקוחות",
    priority: 71,
  },
  {
    slug: "business-development-manager",
    labelEn: "Business Development Manager",
    labelHe: "מנהל פיתוח עסקי",
    priority: 70,
  },
  {
    slug: "operations-manager",
    labelEn: "Operations Manager",
    labelHe: "מנהל תפעול",
    priority: 69,
  },
  {
    slug: "human-resources-manager",
    labelEn: "Human Resources Manager",
    labelHe: "מנהל משאבי אנוש",
    aliases: ["HR Manager"],
    priority: 68,
  },
  {
    slug: "recruiter",
    labelEn: "Recruiter",
    labelHe: "מגייס",
    aliases: ["Talent Acquisition Specialist"],
    priority: 67,
  },
  {
    slug: "office-manager",
    labelEn: "Office Manager",
    labelHe: "מנהל משרד",
    priority: 66,
  },
  {
    slug: "administrative-assistant",
    labelEn: "Administrative Assistant",
    labelHe: "עוזר אדמיניסטרטיבי",
    priority: 65,
  },
  {
    slug: "customer-service-representative",
    labelEn: "Customer Service Representative",
    labelHe: "נציג שירות לקוחות",
    aliases: ["Customer Support Representative", "נציג תמיכה ושירות"],
    priority: 64,
  },
  {
    slug: "technical-support-specialist",
    labelEn: "Technical Support Specialist",
    labelHe: "מומחה תמיכה טכנית",
    aliases: [
      "IT Support",
      "Technical Support Representative",
      "נציג תמיכה טכנית",
    ],
    priority: 63,
  },
  {
    slug: "bookkeeper",
    labelEn: "Bookkeeper",
    labelHe: "מנהל חשבונות",
    priority: 62,
  },
  {
    slug: "accountant",
    labelEn: "Accountant",
    labelHe: "רואה חשבון",
    priority: 61,
  },
];

const skills: Omit<CatalogSeedItem, "kind">[] = [
  ["javascript", "JavaScript", "JavaScript"],
  ["typescript", "TypeScript", "TypeScript"],
  ["react", "React", "React"],
  ["angular", "Angular", "Angular"],
  ["vue", "Vue.js", "Vue.js"],
  ["nodejs", "Node.js", "Node.js"],
  ["python", "Python", "Python"],
  ["java", "Java", "Java"],
  ["csharp", "C#", "C#"],
  ["cplusplus", "C++", "C++"],
  ["go", "Go", "Go"],
  ["rust", "Rust", "Rust"],
  ["swift", "Swift", "Swift"],
  ["kotlin", "Kotlin", "Kotlin"],
  ["sql", "SQL", "SQL"],
  ["postgresql", "PostgreSQL", "PostgreSQL"],
  ["mongodb", "MongoDB", "MongoDB"],
  ["convex", "Convex", "Convex"],
  ["aws", "AWS", "AWS"],
  ["azure", "Microsoft Azure", "Microsoft Azure"],
  ["gcp", "Google Cloud", "Google Cloud"],
  ["docker", "Docker", "Docker"],
  ["kubernetes", "Kubernetes", "Kubernetes"],
  ["terraform", "Terraform", "Terraform"],
  ["cicd", "CI/CD", "CI/CD"],
  ["git", "Git", "Git"],
  ["rest-apis", "REST APIs", "ממשקי REST"],
  ["graphql", "GraphQL", "GraphQL"],
  ["microservices", "Microservices", "מיקרו-שירותים"],
  ["system-design", "System Design", "תכנון מערכות"],
  ["machine-learning", "Machine Learning", "למידת מכונה"],
  ["generative-ai", "Generative AI", "בינה מלאכותית יוצרת"],
  ["data-analysis", "Data Analysis", "ניתוח נתונים"],
  ["data-visualization", "Data Visualization", "הצגת נתונים"],
  ["excel", "Microsoft Excel", "Microsoft Excel"],
  ["power-bi", "Power BI", "Power BI"],
  ["tableau", "Tableau", "Tableau"],
  ["figma", "Figma", "Figma"],
  ["user-research", "User Research", "מחקר משתמשים"],
  ["ux-design", "UX Design", "עיצוב חוויית משתמש"],
  ["ui-design", "UI Design", "עיצוב ממשק משתמש"],
  ["product-management", "Product Management", "ניהול מוצר"],
  ["project-management", "Project Management", "ניהול פרויקטים"],
  ["agile", "Agile", "Agile"],
  ["scrum", "Scrum", "Scrum"],
  ["jira", "Jira", "Jira"],
  ["digital-marketing", "Digital Marketing", "שיווק דיגיטלי"],
  ["seo", "SEO", "SEO"],
  ["content-marketing", "Content Marketing", "שיווק באמצעות תוכן"],
  ["social-media", "Social Media Marketing", "שיווק ברשתות חברתיות"],
  ["google-analytics", "Google Analytics", "Google Analytics"],
  ["sales", "Sales", "מכירות"],
  ["b2b-sales", "B2B Sales", "מכירות B2B"],
  ["customer-success", "Customer Success", "הצלחת לקוחות"],
  ["crm", "CRM", "CRM"],
  ["salesforce", "Salesforce", "Salesforce"],
  ["financial-analysis", "Financial Analysis", "ניתוח פיננסי"],
  ["bookkeeping", "Bookkeeping", "הנהלת חשבונות"],
  ["recruiting", "Recruiting", "גיוס עובדים"],
  ["operations", "Operations", "תפעול"],
  ["leadership", "Leadership", "מנהיגות"],
  ["team-management", "Team Management", "ניהול צוות"],
  ["communication", "Communication", "תקשורת בין-אישית"],
  ["problem-solving", "Problem Solving", "פתרון בעיות"],
  ["presentation", "Presentation Skills", "מיומנויות הצגה"],
  ["negotiation", "Negotiation", "משא ומתן"],
  ["time-management", "Time Management", "ניהול זמן"],
].map(([slug, labelEn, labelHe], index) => ({
  slug,
  labelEn,
  labelHe,
  priority: 100 - index,
}));

export const CATALOG_SEED: CatalogSeedItem[] = [
  ...jobTitles.map((item) => ({ ...item, kind: "jobTitle" as const })),
  ...skills.map((item) => ({ ...item, kind: "skill" as const })),
];
