export type CatalogSeedItem = {
  kind: "jobTitle" | "skill" | "experienceDomain";
  slug: string;
  labelEn: string;
  labelHe: string;
  aliases?: string[];
  priority: number;
};

const jobTitles: Omit<CatalogSeedItem, "kind">[] = [
  {
    slug: "software-engineer",
    labelEn: "Software Engineer",
    labelHe: "מהנדס תוכנה",
    aliases: ["Software Developer", "מפתח תוכנה", "Programmer", "מתכנת"],
    priority: 100,
  },
  {
    slug: "frontend-engineer",
    labelEn: "Frontend Engineer",
    labelHe: "מפתח Frontend",
    aliases: ["Front-end Developer", "מפתח פרונטאנד"],
    priority: 99,
  },
  {
    slug: "backend-engineer",
    labelEn: "Backend Engineer",
    labelHe: "מפתח Backend",
    aliases: ["Back-end Developer", "מפתח בקאנד"],
    priority: 98,
  },
  {
    slug: "fullstack-engineer",
    labelEn: "Full-stack Engineer",
    labelHe: "מפתח Full-stack",
    aliases: ["Full Stack Developer", "מפתח פול סטאק"],
    priority: 97,
  },
  {
    slug: "mobile-developer",
    labelEn: "Mobile Developer",
    labelHe: "מפתח מובייל",
    aliases: ["iOS Developer", "Android Developer"],
    priority: 96,
  },
  {
    slug: "devops-engineer",
    labelEn: "DevOps Engineer",
    labelHe: "מהנדס DevOps",
    priority: 95,
  },
  {
    slug: "data-engineer",
    labelEn: "Data Engineer",
    labelHe: "מהנדס נתונים",
    priority: 94,
  },
  {
    slug: "data-scientist",
    labelEn: "Data Scientist",
    labelHe: "מדען נתונים",
    priority: 93,
  },
  {
    slug: "machine-learning-engineer",
    labelEn: "Machine Learning Engineer",
    labelHe: "מהנדס למידת מכונה",
    aliases: ["ML Engineer", "AI Engineer"],
    priority: 92,
  },
  {
    slug: "qa-engineer",
    labelEn: "QA Engineer",
    labelHe: "מהנדס בדיקות",
    aliases: ["Software Tester", "בודק תוכנה"],
    priority: 91,
  },
  {
    slug: "automation-engineer",
    labelEn: "Automation Engineer",
    labelHe: "מהנדס אוטומציה",
    aliases: ["QA Automation Engineer"],
    priority: 90,
  },
  {
    slug: "security-engineer",
    labelEn: "Security Engineer",
    labelHe: "מהנדס אבטחת מידע",
    aliases: ["Cybersecurity Engineer"],
    priority: 89,
  },
  {
    slug: "cloud-engineer",
    labelEn: "Cloud Engineer",
    labelHe: "מהנדס ענן",
    priority: 88,
  },
  {
    slug: "solutions-architect",
    labelEn: "Solutions Architect",
    labelHe: "ארכיטקט פתרונות",
    priority: 87,
  },
  {
    slug: "engineering-manager",
    labelEn: "Engineering Manager",
    labelHe: "מנהל פיתוח",
    aliases: ["R&D Manager", "מנהל הנדסה"],
    priority: 86,
  },
  {
    slug: "product-manager",
    labelEn: "Product Manager",
    labelHe: "מנהל מוצר",
    priority: 85,
  },
  {
    slug: "project-manager",
    labelEn: "Project Manager",
    labelHe: "מנהל פרויקטים",
    priority: 84,
  },
  {
    slug: "program-manager",
    labelEn: "Program Manager",
    labelHe: "מנהל תוכניות",
    priority: 83,
  },
  {
    slug: "product-designer",
    labelEn: "Product Designer",
    labelHe: "מעצב מוצר",
    priority: 82,
  },
  {
    slug: "ux-ui-designer",
    labelEn: "UX/UI Designer",
    labelHe: "מעצב UX/UI",
    priority: 81,
  },
  {
    slug: "graphic-designer",
    labelEn: "Graphic Designer",
    labelHe: "מעצב גרפי",
    priority: 80,
  },
  {
    slug: "business-analyst",
    labelEn: "Business Analyst",
    labelHe: "אנליסט עסקי",
    priority: 79,
  },
  {
    slug: "data-analyst",
    labelEn: "Data Analyst",
    labelHe: "אנליסט נתונים",
    priority: 78,
  },
  {
    slug: "financial-analyst",
    labelEn: "Financial Analyst",
    labelHe: "אנליסט פיננסי",
    priority: 77,
  },
  {
    slug: "marketing-manager",
    labelEn: "Marketing Manager",
    labelHe: "מנהל שיווק",
    priority: 76,
  },
  {
    slug: "ecommerce-manager",
    labelEn: "E-commerce Manager",
    labelHe: "מנהל E-commerce",
    aliases: [
      "Ecommerce Manager",
      "E-Commerce Manager",
      "מנהל איקומרס",
      "מנהל מסחר אלקטרוני",
    ],
    priority: 76,
  },
  {
    slug: "website-manager",
    labelEn: "Website Manager",
    labelHe: "מנהל אתר",
    aliases: ["Web Manager", "E-commerce Website Manager", "מנהל אתר איקומרס"],
    priority: 76,
  },
  {
    slug: "ecommerce-operations-manager",
    labelEn: "E-commerce Operations Manager",
    labelHe: "מנהל תפעול E-commerce",
    aliases: [
      "Ecommerce Operations Manager",
      "Digital Commerce Operations Manager",
      "מנהל תפעול איקומרס",
    ],
    priority: 76,
  },
  {
    slug: "digital-marketing-specialist",
    labelEn: "Digital Marketing Specialist",
    labelHe: "מומחה שיווק דיגיטלי",
    priority: 75,
  },
  {
    slug: "content-writer",
    labelEn: "Content Writer",
    labelHe: "כותב תוכן",
    priority: 74,
  },
  {
    slug: "sales-manager",
    labelEn: "Sales Manager",
    labelHe: "מנהל מכירות",
    priority: 73,
  },
  {
    slug: "account-manager",
    labelEn: "Account Manager",
    labelHe: "מנהל לקוחות",
    priority: 72,
  },
  {
    slug: "customer-success-manager",
    labelEn: "Customer Success Manager",
    labelHe: "מנהל הצלחת לקוחות",
    priority: 71,
  },
  {
    slug: "business-development-manager",
    labelEn: "Business Development Manager",
    labelHe: "מנהל פיתוח עסקי",
    priority: 70,
  },
  {
    slug: "operations-manager",
    labelEn: "Operations Manager",
    labelHe: "מנהל תפעול",
    priority: 69,
  },
  {
    slug: "human-resources-manager",
    labelEn: "Human Resources Manager",
    labelHe: "מנהל משאבי אנוש",
    aliases: ["HR Manager"],
    priority: 68,
  },
  {
    slug: "recruiter",
    labelEn: "Recruiter",
    labelHe: "מגייס",
    aliases: ["Talent Acquisition Specialist"],
    priority: 67,
  },
  {
    slug: "office-manager",
    labelEn: "Office Manager",
    labelHe: "מנהל משרד",
    priority: 66,
  },
  {
    slug: "administrative-assistant",
    labelEn: "Administrative Assistant",
    labelHe: "עוזר אדמיניסטרטיבי",
    priority: 65,
  },
  {
    slug: "customer-service-representative",
    labelEn: "Customer Service Representative",
    labelHe: "נציג שירות לקוחות",
    aliases: ["Customer Support Representative", "נציג תמיכה ושירות"],
    priority: 64,
  },
  {
    slug: "technical-support-specialist",
    labelEn: "Technical Support Specialist",
    labelHe: "מומחה תמיכה טכנית",
    aliases: [
      "IT Support",
      "Technical Support Representative",
      "נציג תמיכה טכנית",
    ],
    priority: 63,
  },
  {
    slug: "bookkeeper",
    labelEn: "Bookkeeper",
    labelHe: "מנהל חשבונות",
    priority: 62,
  },
  {
    slug: "accountant",
    labelEn: "Accountant",
    labelHe: "רואה חשבון",
    priority: 61,
  },
];

// Only equivalent names belong here. Related skills remain separate concepts.
const SKILL_ALIASES: Record<string, string[]> = {
  javascript: [
    "JS",
    "Java Script",
    "ECMAScript",
    "ג'אווהסקריפט",
    "ג׳אווהסקריפט",
  ],
  typescript: ["TS", "Type Script"],
  react: ["React.js", "ReactJS", "React JS", "ריאקט"],
  "react-native": ["ReactNative", "React-Native", "ריאקט נייטיב"],
  nextjs: ["NextJS", "Next JS", "Next.js"],
  nodejs: ["NodeJS", "Node JS", "Node.js"],
  vue: ["Vue", "VueJS", "Vue JS"],
  csharp: ["C Sharp", "CSharp"],
  cplusplus: ["C Plus Plus", "CPP"],
  go: ["Golang"],
  postgresql: ["Postgres"],
  mongodb: ["Mongo DB"],
  aws: ["Amazon Web Services"],
  azure: ["Azure"],
  gcp: ["GCP", "Google Cloud Platform"],
  kubernetes: ["K8s"],
  "rest-apis": ["REST API", "RESTful API", "RESTful APIs"],
  cicd: ["CI CD", "Continuous Integration and Continuous Delivery"],
  "machine-learning": ["ML"],
  "generative-ai": ["GenAI", "Gen AI"],
  excel: ["Excel", "אקסל"],
  "power-bi": ["PowerBI"],
  "ux-design": ["User Experience Design"],
  "ui-design": ["User Interface Design"],
  seo: ["Search Engine Optimization", "קידום אתרים"],
  crm: ["Customer Relationship Management"],
  communication: ["Interpersonal Skills", "יחסי אנוש", "תקשורת בינאישית"],
  "verbal-communication": [
    "Oral Communication",
    "Verbal Expression",
    "כושר התבטאות",
    "יכולת התבטאות",
    "יכולת ביטוי בעל פה",
    "כושר ביטוי בעל פה",
    "תקשורת בעל פה",
  ],
  "public-speaking": ["דיבור מול קהל", "יכולת עמידה מול קהל"],
  "written-communication": [
    "Written Expression",
    "יכולת ביטוי בכתב",
    "כושר התבטאות בכתב",
  ],
  "problem-solving": ["Problem-Solving", "יכולת פתרון בעיות"],
  html: ["HTML5"],
  css: ["CSS3"],
  expressjs: ["Express", "ExpressJS"],
  nestjs: ["Nest.js"],
  dotnet: ["dotnet", "Dot Net"],
  tailwind: ["Tailwind"],
  drizzle: ["Drizzle"],
  networking: ["Networking", "רשתות מחשבים"],
  "priority-erp": ["Priority", "פריוריטי"],
  photoshop: ["Photoshop", "פוטושופ"],
  illustrator: ["Illustrator"],
  "customer-service": ["Customer Support"],
  "claims-handling": ["Claims Processing"],
  "make-com": ["Integromat"],
};

const skills: Omit<CatalogSeedItem, "kind">[] = [
  ["javascript", "JavaScript", "JavaScript"],
  ["typescript", "TypeScript", "TypeScript"],
  ["react", "React", "React"],
  ["angular", "Angular", "Angular"],
  ["vue", "Vue.js", "Vue.js"],
  ["nodejs", "Node.js", "Node.js"],
  ["python", "Python", "Python"],
  ["java", "Java", "Java"],
  ["csharp", "C#", "C#"],
  ["cplusplus", "C++", "C++"],
  ["go", "Go", "Go"],
  ["rust", "Rust", "Rust"],
  ["swift", "Swift", "Swift"],
  ["kotlin", "Kotlin", "Kotlin"],
  ["sql", "SQL", "SQL"],
  ["postgresql", "PostgreSQL", "PostgreSQL"],
  ["mongodb", "MongoDB", "MongoDB"],
  ["convex", "Convex", "Convex"],
  ["aws", "AWS", "AWS"],
  ["azure", "Microsoft Azure", "Microsoft Azure"],
  ["gcp", "Google Cloud", "Google Cloud"],
  ["docker", "Docker", "Docker"],
  ["kubernetes", "Kubernetes", "Kubernetes"],
  ["terraform", "Terraform", "Terraform"],
  ["cicd", "CI/CD", "CI/CD"],
  ["git", "Git", "Git"],
  ["rest-apis", "REST APIs", "ממשקי REST"],
  ["graphql", "GraphQL", "GraphQL"],
  ["microservices", "Microservices", "מיקרו-שירותים"],
  ["system-design", "System Design", "תכנון מערכות"],
  ["machine-learning", "Machine Learning", "למידת מכונה"],
  ["generative-ai", "Generative AI", "בינה מלאכותית יוצרת"],
  ["data-analysis", "Data Analysis", "ניתוח נתונים"],
  ["data-visualization", "Data Visualization", "הצגת נתונים"],
  ["excel", "Microsoft Excel", "Microsoft Excel"],
  ["power-bi", "Power BI", "Power BI"],
  ["tableau", "Tableau", "Tableau"],
  ["figma", "Figma", "Figma"],
  ["user-research", "User Research", "מחקר משתמשים"],
  ["ux-design", "UX Design", "עיצוב חוויית משתמש"],
  ["ui-design", "UI Design", "עיצוב ממשק משתמש"],
  ["product-management", "Product Management", "ניהול מוצר"],
  ["project-management", "Project Management", "ניהול פרויקטים"],
  ["agile", "Agile", "Agile"],
  ["scrum", "Scrum", "Scrum"],
  ["jira", "Jira", "Jira"],
  ["digital-marketing", "Digital Marketing", "שיווק דיגיטלי"],
  ["seo", "SEO", "SEO"],
  ["content-marketing", "Content Marketing", "שיווק באמצעות תוכן"],
  ["social-media", "Social Media Marketing", "שיווק ברשתות חברתיות"],
  ["google-analytics", "Google Analytics", "Google Analytics"],
  ["sales", "Sales", "מכירות"],
  ["b2b-sales", "B2B Sales", "מכירות B2B"],
  ["customer-success", "Customer Success", "הצלחת לקוחות"],
  ["crm", "CRM", "CRM"],
  ["salesforce", "Salesforce", "Salesforce"],
  ["financial-analysis", "Financial Analysis", "ניתוח פיננסי"],
  ["bookkeeping", "Bookkeeping", "הנהלת חשבונות"],
  ["recruiting", "Recruiting", "גיוס עובדים"],
  ["operations", "Operations", "תפעול"],
  ["leadership", "Leadership", "מנהיגות"],
  ["team-management", "Team Management", "ניהול צוות"],
  ["communication", "Interpersonal Communication", "תקשורת בין-אישית"],
  ["verbal-communication", "Verbal Communication", "כושר ביטוי"],
  ["public-speaking", "Public Speaking", "עמידה מול קהל"],
  ["written-communication", "Written Communication", "כושר ביטוי בכתב"],
  ["react-native", "React Native", "React Native"],
  ["nextjs", "Next.js", "Next.js"],
  ["html", "HTML", "HTML"],
  ["css", "CSS", "CSS"],
  ["problem-solving", "Problem Solving", "פתרון בעיות"],
  ["presentation", "Presentation Skills", "מיומנויות הצגה"],
  ["negotiation", "Negotiation", "משא ומתן"],
  ["time-management", "Time Management", "ניהול זמן"],
  ["svelte", "Svelte", "Svelte"],
  ["nuxt", "Nuxt", "Nuxt"],
  ["expressjs", "Express.js", "Express.js"],
  ["nestjs", "NestJS", "NestJS"],
  ["fastify", "Fastify", "Fastify"],
  ["django", "Django", "Django"],
  ["flask", "Flask", "Flask"],
  ["fastapi", "FastAPI", "FastAPI"],
  ["spring-boot", "Spring Boot", "Spring Boot"],
  ["dotnet", ".NET", ".NET"],
  ["aspnet", "ASP.NET", "ASP.NET"],
  ["php", "PHP", "PHP"],
  ["laravel", "Laravel", "Laravel"],
  ["ruby", "Ruby", "Ruby"],
  ["rails", "Ruby on Rails", "Ruby on Rails"],
  ["dart", "Dart", "Dart"],
  ["flutter", "Flutter", "Flutter"],
  ["c", "C", "C"],
  ["scala", "Scala", "Scala"],
  ["bash", "Bash", "Bash"],
  ["powershell", "PowerShell", "PowerShell"],
  ["linux", "Linux", "Linux"],
  ["tailwind", "Tailwind CSS", "Tailwind CSS"],
  ["sass", "Sass", "Sass"],
  ["webpack", "Webpack", "Webpack"],
  ["vite", "Vite", "Vite"],
  ["redux", "Redux", "Redux"],
  ["zustand", "Zustand", "Zustand"],
  ["trpc", "tRPC", "tRPC"],
  ["zod", "Zod", "Zod"],
  ["prisma", "Prisma", "Prisma"],
  ["drizzle", "Drizzle ORM", "Drizzle ORM"],
  ["mysql", "MySQL", "MySQL"],
  ["sqlite", "SQLite", "SQLite"],
  ["redis", "Redis", "Redis"],
  ["elasticsearch", "Elasticsearch", "Elasticsearch"],
  ["firebase", "Firebase", "Firebase"],
  ["supabase", "Supabase", "Supabase"],
  ["snowflake", "Snowflake", "Snowflake"],
  ["bigquery", "BigQuery", "BigQuery"],
  ["kafka", "Apache Kafka", "Apache Kafka"],
  ["rabbitmq", "RabbitMQ", "RabbitMQ"],
  ["spark", "Apache Spark", "Apache Spark"],
  ["airflow", "Apache Airflow", "Apache Airflow"],
  ["dbt", "dbt", "dbt"],
  ["pandas", "pandas", "pandas"],
  ["numpy", "NumPy", "NumPy"],
  ["pytorch", "PyTorch", "PyTorch"],
  ["tensorflow", "TensorFlow", "TensorFlow"],
  ["scikit-learn", "scikit-learn", "scikit-learn"],
  ["statistics", "Statistics", "סטטיסטיקה"],
  ["etl", "ETL", "ETL"],
  ["jest", "Jest", "Jest"],
  ["vitest", "Vitest", "Vitest"],
  ["playwright", "Playwright", "Playwright"],
  ["cypress", "Cypress", "Cypress"],
  ["selenium", "Selenium", "Selenium"],
  ["postman", "Postman", "Postman"],
  ["manual-testing", "Manual Testing", "בדיקות ידניות"],
  ["test-automation", "Test Automation", "אוטומציית בדיקות"],
  ["jenkins", "Jenkins", "Jenkins"],
  ["github-actions", "GitHub Actions", "GitHub Actions"],
  ["gitlab", "GitLab", "GitLab"],
  ["ansible", "Ansible", "Ansible"],
  ["helm", "Helm", "Helm"],
  ["nginx", "Nginx", "Nginx"],
  ["cloudflare", "Cloudflare", "Cloudflare"],
  ["vercel", "Vercel", "Vercel"],
  ["prometheus", "Prometheus", "Prometheus"],
  ["grafana", "Grafana", "Grafana"],
  ["datadog", "Datadog", "Datadog"],
  ["sentry", "Sentry", "Sentry"],
  ["posthog", "PostHog", "PostHog"],
  ["oauth", "OAuth", "OAuth"],
  ["webhooks", "Webhooks", "Webhooks"],
  ["websockets", "WebSockets", "WebSockets"],
  ["twilio", "Twilio", "Twilio"],
  ["ffmpeg", "FFmpeg", "FFmpeg"],
  ["tcp-ip", "TCP/IP", "TCP/IP"],
  ["dns", "DNS", "DNS"],
  ["networking", "Computer Networking", "תקשורת מחשבים"],
  ["information-security", "Information Security", "אבטחת מידע"],
  ["penetration-testing", "Penetration Testing", "בדיקות חדירה"],
  ["incident-response", "Incident Response", "תגובה לאירועי אבטחה"],
  ["siem", "SIEM", "SIEM"],
  ["active-directory", "Active Directory", "Active Directory"],
  ["microsoft-365", "Microsoft 365", "Microsoft 365"],
  ["google-workspace", "Google Workspace", "Google Workspace"],
  ["technical-support", "Technical Support", "תמיכה טכנית"],
  ["customer-service", "Customer Service", "שירות לקוחות"],
  ["zendesk", "Zendesk", "Zendesk"],
  ["hubspot", "HubSpot", "HubSpot"],
  ["sap", "SAP", "SAP"],
  ["priority-erp", "Priority ERP", "Priority ERP"],
  ["netsuite", "NetSuite", "NetSuite"],
  ["quickbooks", "QuickBooks", "QuickBooks"],
  ["payroll", "Payroll", "חשבות שכר"],
  ["budgeting", "Budget Management", "ניהול תקציב"],
  ["accounting", "Accounting", "חשבונאות"],
  ["auditing", "Auditing", "ביקורת חשבונות"],
  ["procurement", "Procurement", "רכש"],
  ["supply-chain", "Supply Chain Management", "ניהול שרשרת אספקה"],
  ["inventory", "Inventory Management", "ניהול מלאי"],
  ["logistics", "Logistics", "לוגיסטיקה"],
  ["quality-control", "Quality Control", "בקרת איכות"],
  ["lean", "Lean Manufacturing", "ייצור רזה"],
  ["six-sigma", "Six Sigma", "Six Sigma"],
  ["autocad", "AutoCAD", "AutoCAD"],
  ["solidworks", "SolidWorks", "SolidWorks"],
  ["revit", "Revit", "Revit"],
  ["plc", "PLC Programming", "תכנות PLC"],
  ["photoshop", "Adobe Photoshop", "Adobe Photoshop"],
  ["illustrator", "Adobe Illustrator", "Adobe Illustrator"],
  ["indesign", "Adobe InDesign", "Adobe InDesign"],
  ["premiere", "Adobe Premiere Pro", "Adobe Premiere Pro"],
  ["after-effects", "Adobe After Effects", "Adobe After Effects"],
  ["blender", "Blender", "Blender"],
  ["canva", "Canva", "Canva"],
  ["wordpress", "WordPress", "WordPress"],
  ["shopify", "Shopify", "Shopify"],
  ["google-ads", "Google Ads", "Google Ads"],
  ["meta-ads", "Meta Ads", "Meta Ads"],
  ["copywriting", "Copywriting", "קופירייטינג"],
  ["email-marketing", "Email Marketing", "שיווק בדואר אלקטרוני"],
  ["campaign-management", "Campaign Management", "ניהול קמפיינים"],
  ["business-development", "Business Development", "פיתוח עסקי"],
  ["account-management", "Account Management", "ניהול תיקי לקוחות"],
  ["training", "Training and Instruction", "הדרכה"],
  ["conflict-resolution", "Conflict Resolution", "פתרון קונפליקטים"],
  ["attention-detail", "Attention to Detail", "תשומת לב לפרטים"],
  ["medical-records", "Medical Documentation", "תיעוד רפואי"],
  ["patient-care", "Patient Care", "טיפול בחולים"],
  ["lesson-planning", "Lesson Planning", "תכנון שיעורים"],
  ["classroom-management", "Classroom Management", "ניהול כיתה"],
  ["legal-research", "Legal Research", "מחקר משפטי"],
  ["contract-drafting", "Contract Drafting", "ניסוח חוזים"],
  ["claims-handling", "Claims Handling", "טיפול בתביעות"],
  ["insurance-underwriting", "Insurance Underwriting", "חיתום ביטוח"],
  ["accessibility", "Web Accessibility", "נגישות אתרים"],
  ["internationalization", "Internationalization", "בינאום תוכנה"],
  ["zapier", "Zapier", "Zapier"],
  ["make-com", "Make.com", "Make.com"],
].map(([slug, labelEn, labelHe], index) => ({
  slug,
  labelEn,
  labelHe,
  aliases: SKILL_ALIASES[slug] ?? [],
  priority: 100 - index,
}));

const experienceDomains: Omit<CatalogSeedItem, "kind">[] = [
  ["software-development", "Software Development", "פיתוח תוכנה"],
  ["customer-service", "Customer Service", "שירות לקוחות"],
  ["insurance", "Insurance", "ביטוח"],
  ["sales", "Sales", "מכירות"],
  ["marketing", "Marketing", "שיווק"],
  ["data-analytics", "Data Analytics", "ניתוח נתונים"],
  ["finance-accounting", "Finance and Accounting", "כספים וחשבונאות"],
  ["human-resources", "Human Resources", "משאבי אנוש"],
  ["logistics", "Logistics", "לוגיסטיקה"],
  ["product-management", "Product Management", "ניהול מוצר"],
  ["design", "Design", "עיצוב"],
  ["healthcare", "Healthcare", "בריאות"],
  ["education-teaching", "Education and Teaching", "חינוך והוראה"],
  ["cybersecurity", "Cybersecurity", "אבטחת מידע"],
  ["construction", "Construction", "בנייה"],
  ["manufacturing", "Manufacturing", "ייצור ותעשייה"],
  ["retail", "Retail", "קמעונאות"],
  ["hospitality", "Hospitality and Tourism", "מלונאות ותיירות"],
  ["food-beverage", "Food and Beverage", "מזון ומשקאות"],
  ["legal", "Legal Services", "שירותים משפטיים"],
  ["engineering", "Engineering", "הנדסה"],
  ["real-estate", "Real Estate", "נדל״ן"],
  ["automotive", "Automotive", "רכב"],
  ["telecommunications", "Telecommunications", "תקשורת"],
  ["it-support", "IT Support", "תמיכת IT"],
  ["biotechnology", "Biotechnology", "ביוטכנולוגיה"],
  ["pharmaceuticals", "Pharmaceuticals", "פארמה"],
  ["social-services", "Social Services", "שירותים חברתיים"],
  ["administration", "Administration", "אדמיניסטרציה"],
  ["public-sector", "Public Sector", "מגזר ציבורי"],
  ["energy", "Energy", "אנרגיה"],
  ["agriculture", "Agriculture", "חקלאות"],
  ["media", "Media and Entertainment", "מדיה ובידור"],
  ["transportation", "Transportation", "תחבורה"],
].map(([slug, labelEn, labelHe], index) => ({
  slug: "experience-domain:" + slug,
  labelEn,
  labelHe,
  priority: 100 - index,
}));

const additionalJobTitles: Omit<CatalogSeedItem, "kind">[] = [
  ["technical-writer", "Technical Writer", "כתב טכני"],
  ["it-support-specialist", "IT Support Specialist", "איש תמיכת IT"],
  ["systems-administrator", "Systems Administrator", "מנהל מערכות"],
  ["network-engineer", "Network Engineer", "מהנדס רשתות"],
  ["soc-analyst", "SOC Analyst", "אנליסט SOC"],
  ["penetration-tester", "Penetration Tester", "בודק חדירות"],
  ["cloud-architect", "Cloud Architect", "ארכיטקט ענן"],
  ["embedded-engineer", "Embedded Software Engineer", "מהנדס תוכנה משובצת"],
  ["electrical-engineer", "Electrical Engineer", "מהנדס חשמל"],
  ["mechanical-engineer", "Mechanical Engineer", "מהנדס מכונות"],
  ["industrial-engineer", "Industrial Engineer", "מהנדס תעשייה וניהול"],
  ["civil-engineer", "Civil Engineer", "מהנדס אזרחי"],
  ["architect", "Architect", "אדריכל"],
  ["interior-designer", "Interior Designer", "מעצב פנים"],
  ["video-editor", "Video Editor", "עורך וידאו"],
  ["motion-designer", "Motion Designer", "מעצב תנועה"],
  ["social-media-manager", "Social Media Manager", "מנהל רשתות חברתיות"],
  ["seo-specialist", "SEO Specialist", "מומחה SEO"],
  ["ppc-specialist", "PPC Specialist", "מנהל קמפיינים ממומנים"],
  ["copywriter", "Copywriter", "קופירייטר"],
  ["sales-representative", "Sales Representative", "נציג מכירות"],
  [
    "sales-development-representative",
    "Sales Development Representative",
    "נציג פיתוח מכירות",
  ],
  ["store-manager", "Store Manager", "מנהל חנות"],
  ["cashier", "Cashier", "קופאי"],
  ["warehouse-worker", "Warehouse Worker", "מחסנאי"],
  ["warehouse-manager", "Warehouse Manager", "מנהל מחסן"],
  ["logistics-coordinator", "Logistics Coordinator", "רכז לוגיסטיקה"],
  ["procurement-specialist", "Procurement Specialist", "קניין רכש"],
  ["supply-chain-manager", "Supply Chain Manager", "מנהל שרשרת אספקה"],
  ["delivery-driver", "Delivery Driver", "נהג חלוקה"],
  ["payroll-specialist", "Payroll Specialist", "חשב שכר"],
  ["financial-controller", "Financial Controller", "חשב"],
  ["insurance-agent", "Insurance Agent", "סוכן ביטוח"],
  ["claims-specialist", "Claims Specialist", "נציג תביעות"],
  ["underwriter", "Insurance Underwriter", "חתם ביטוח"],
  ["lawyer", "Lawyer", "עורך דין"],
  ["paralegal", "Paralegal", "עוזר משפטי"],
  ["teacher", "Teacher", "מורה"],
  ["teaching-assistant", "Teaching Assistant", "סייע הוראה"],
  ["trainer", "Training Specialist", "מדריך"],
  ["registered-nurse", "Registered Nurse", "אח מוסמך"],
  ["medical-secretary", "Medical Secretary", "מזכיר רפואי"],
  ["laboratory-technician", "Laboratory Technician", "טכנאי מעבדה"],
  ["social-worker", "Social Worker", "עובד סוציאלי"],
  ["physiotherapist", "Physiotherapist", "פיזיותרפיסט"],
  ["receptionist", "Receptionist", "פקיד קבלה"],
  ["restaurant-manager", "Restaurant Manager", "מנהל מסעדה"],
  ["chef", "Chef", "שף"],
  ["cook", "Cook", "טבח"],
  ["waiter", "Waiter", "מלצר"],
  ["barista", "Barista", "בריסטה"],
  ["hotel-manager", "Hotel Manager", "מנהל מלון"],
  ["electrician", "Electrician", "חשמלאי"],
  ["maintenance-technician", "Maintenance Technician", "טכנאי אחזקה"],
  ["production-worker", "Production Worker", "עובד ייצור"],
  ["quality-inspector", "Quality Inspector", "מבקר איכות"],
  ["construction-manager", "Construction Manager", "מנהל עבודה בבנייה"],
  ["security-guard", "Security Guard", "מאבטח"],
  ["executive-assistant", "Executive Assistant", "עוזר אישי"],
  ["hr-coordinator", "HR Coordinator", "רכז משאבי אנוש"],
].map(([slug, labelEn, labelHe], index) => ({
  slug,
  labelEn,
  labelHe,
  priority: 50 - index,
}));

export const CATALOG_SEED: CatalogSeedItem[] = [
  ...jobTitles.map((item) => ({ ...item, kind: "jobTitle" as const })),
  ...additionalJobTitles.map((item) => ({
    ...item,
    kind: "jobTitle" as const,
  })),
  ...skills.map((item) => ({ ...item, kind: "skill" as const })),
  ...experienceDomains.map((item) => ({
    ...item,
    kind: "experienceDomain" as const,
  })),
];
